- .github/workflows/deploy_pypi.yml
Needs to add create, and add the token from PyPi. You have to do it @juanep97
This will trigger the deployment of IOP4 to PyPi every time a new release/tag is created.
> Add github action to deploy to PyPi

- .github/workflows/ci.yml
- README.md
Tests should pass in less than 1 hour, if it keeps running more it is because it is stuck (#29).
When new commits are added to a branch in a PR, previous ones should be discarded. Since they take some time to run it creates a mess of messages arriving at different times.
> Add a time out for actions in CI and cancel previous jobs for the same PR

- iop4lib/instruments/dipol.py
- iop4lib/iop4.py
Changes:
- iop4.py command was ignoring filelocs_to_process, which is supposed to be the selected file list by the command line options.
- Fix dipol quads not handling the case where no quads are found in the image. This was causing an exception and therefore aborting the reduction of that specific file, instead of just returning success=False and continuing with another attempt.
> Fix dipol quads, iop4 command

- README.md
- config/config.example.yaml
- iop4api/static/iop4api/base.css
- iop4api/static/iop4api/gui.js
- iop4api/templates/iop4api/index.html
- iop4api/templates/iop4api/logs.html
- iop4api/views/index.py
- iop4api/views/log.py
- iop4lib/config.py
- iop4lib/db/epoch.py
- iop4lib/iop4.py
- iop4lib/utils/astrometry.py
- iop4lib/utils/parallel.py
- tests/test_caha_cafos.py
- tests/test_osnt090_andor.py
This PR:
- adds support for overriding any config option from the command line as `iop4 -o option1=value1 -o option2=value [...]`.
- improves the filtering and highlighting by a search string in the web gui log viewer. 
Now it correctly highlights any string without breaking the html log, and the page does not become unresponsive when filtering and highlighting big logs. It also starts showing the log as it receives it, instead of loading it whole first.
- adds support for showing multiple logs in the web. Now logs are stored in the `[datadir]/logs/` directory, and the portal allows selecting any log file to display. This will allow datachekers to inspect the logs from different and previous runs of iop4.
> improve iop4 cmd config options and log viewing

- MANIFEST.in
excluding the `_dev_version` and github-related folders.
This tries to solve the appearance of the warning:
```
/tmp/build-env-38jhk5t9/lib/python3.10/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'iop4lib._dev_version' is absent from the `packages` configuration.
```
when building the package.
> Add MANIFEST.in file for packaging

- pyproject.toml
I do not know if this will help with the last warning reported in #42. Just in case, forcing the use of the latest version.
EDIT: The message is still there...
That warning during the wheel build seems to be harmless though (https://github.com/search?q=repo%3Apypa%2Fsetuptools_scm+listing+git+files+failed&type=issues)
> Bump setuptools_scm version

- iop4lib/config.py
- iop4lib/iop4.py
As the title says, this PR adds the `iop4 --check-config` option to check that there are no missing keys in the config file by comparing it to the example one. This is useful to make sure that the used config file is up to date with the iop4 version.
> Add iop4 cmd option to check config file

- iop4lib/db/epoch.py
We have found that in some cases several files in an epoch have the same juliandate. This should not happen (it is a problem with the data), but when it does, it causes an exception in make_polarimetry_groups. 
For the case of making the polarimetry groups, a workaround can be to sort by filename too, to make sure that if there are several groups where all files have the same juliandate, the files from each polarimetry cycle are not mixed. 
For example: even if there are two files for the same object and angle and they have the same date, the filename will distinguish if they belong to one cycle or other (Mrk241_0001R.fit vs Mrk241_0017R.fit).
This will not fix the fact that when the results are computed for those files, there will be several measurements for the same exact date and time. …
> unhandled exception in make_polarimetry_groups due to wrong data

- iop4lib/instruments/dipol.py
- iop4lib/instruments/dipol_astrometry.yaml
- pyproject.toml
Defining the parameters and the logic for astrometric calibration of DIPOL polarimetry images inside the code of the DIPOL class is too messy, in this PR I propose to define the methods and parameters to try in a separate config file.
> decision tree for dipol astrometry

- iop4lib/instruments/cafos.py
- iop4lib/instruments/instrument.py
- iop4lib/utils/sourcepairing.py
- tests/test_caha_cafos.py
This improves astrometric calibration of CAFOS polarimetry images using the distance between pairs computed from already calibrated images.
The mean and std was computed by executing the following commands in the IOP4 IPython terminal: 
```
In [1]: qs = ReducedFit.objects.filter(flags__has=ReducedFit.FLAGS.BUILT_REDUCED, instrument="CAFOS2.2").all()
In [2]: np.mean([redf.astrometry_info[-1]['seg_disp_sign'] for redf in qs[len(qs)-300:len(qs)-1]], axis=0)
In [3]: np.std([redf.astrometry_info[-1]['seg_disp_sign'] for redf in qs[len(qs)-300:len(qs)-1]], axis=0)
```
By using precomputed distances from already calibrated images, it increases the success rate for images with low number of stars where blind pair matching might fail.
> Improve CAFOS pairs matching

- iop4api/static/iop4api/gui.js
- iop4api/templates/iop4api/index.html
- iop4api/templates/iop4api/plot.html
- iop4api/views/plot.py
The flag gui was setting `bad photometry` as `1 << 0`; while the DB definition was `1 << 1`. This PR fixes the web gui to match the definition in `PhotoPolResult.FLAGS`.
> Fix flags in web gui

- docs/data_reduction_details.rst
- iop4lib/enums.py
- iop4lib/instruments/__init__.py
- iop4lib/instruments/cafos.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
- iop4lib/instruments/osn_cameras.py
- iop4lib/telescopes/telescope.py
This PR adapts IOP4 to work on old data (2007-2021/2022):
- Adds old CAFOS keywords that were not recognized.
- Implements the old OSN T090 camera (RoperT90)
> Adapt IOP4 to work on historic (2007-2021/22) data

- iop4lib/utils/parallel.py
Tests in macOS were failing at the parallel polarimetry step:
```
INFO     iop4lib.db.epoch:epoch.py:634 <Epoch 2 | CAHA-T220/2022-09-18>: computing relative polarimetry over 1 polarimetry groups.
DEBUG    iop4lib.db.epoch:epoch.py:635 <Epoch 2 | CAHA-T220/2022-09-18>: groupkeys_L=[{'kwobj': '2200+420', 'instrument': 'CAFOS2.2', 'band': 'R', 'exptime': 10.0}]
Process SpawnPoolWorker-6:
Traceback (most recent call last):
File "/Users/juan/miniconda3/envs/iop4/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/Users/juan/miniconda3/envs/iop4/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/Users/juan/miniconda3/envs/iop4/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get() …
```
> fix tests in macOS

- iop4lib/instruments/cafos.py
This PR enables simple CAFOS photometry (images without pairs), which were not considered previously, since we extracted photometry results from the polarimetry groups (albeit with a higher error). It also enables other bands than R for CAFOS.
> CAFOS: enable simple photometry, more bands

- iop4lib/iop4_night_summary.py
The sender address does not need to accept email, the replies should be to the responsible contact person.
> Add reply-to header to night summary email

- .github/workflows/docs.yml
This tries to fix #95, caused by a bug in the checkout action (github.com/actions/checkout/issues/882).
> Fix release title in docs deployment to GitHub pages

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- README.md
- config/config.example.yaml
- docs/conf.py
- iop4api/templates/iop4api/about.html
- iop4lib/config.example.yaml
- iop4lib/config.py
- iop4lib/iop4.py
- pyproject.toml
- tests/conftest.py
- tests/test_generic.py
- Allow specifying a different configuration file and overriding config options, both with environment variables (for all iop4lib-related processes) and with `-o` options to the `iop4` command (which takes preference).
- Simplify test configuration by using `~/iop4testdata` as path.
- Work only with the test dataset that indicates the right version in the filename (`iop4testdata.{{md5}}.tar.gz`), save time skipping the md5 sum check (~1-2min).
- Automatically download test dataset if needed.
- The CI workflows now use the test dataset file provided by the runner, in the same way as the astrometry index files are provided, which saves some time (~1-2min).
> Simplify IOP4 and tests configuration

- iop4lib/iop4_night_summary.html
Avoid this in the night summary
> Fix unintended line wrap in night summary

- iop4api/templates/iop4api/about.html
- tests/conftest.py
- tests/test_web.py
In this PR:
- Bug fix: the index page template was requesting the reverse for `iop4api:docs` in production too, but this only exists in debug mode.
- Add tests for the web interface. At the moment, it only checks that the index page can be viewed (i.e. we don't get an error immediately).
> Tests for the web interface

- iop4lib/iop4.py
Removes the not very useful `--retry-failed` and `--reclassify-rawfits`. Tasks like those are better done in custom scripts or in the interactive cli. They are hard to implement in a way that it is useful (you need to change the code to affect the result), they did not allow selecting a subset, etc.
> iop4.py: simplify cli options

- .github/workflows/ci.yml
- iop4lib/instruments/dipol.py
Improves DIPOL quad matching by requiring that matched quads cover a minimum area of the image.
This avoids quad matches that don't determine well the transformation between the images, and/or that happen to match fake sources very close to real sources.
> Improve DIPOL quad matching

- docs/serving_iop4_in_production.rst
- iop4lib/iop4_night_summary.html
- iop4lib/iop4_night_summary.py
This PR improves the night summary script by:
- using the same instrument color code in all plots. Previously, different plots in the same summary were choosing the colors independently, which was confusing when looking at the plots.
- showing a warning if the specified return code of the iop4 command is not zero. Previously, a fatal error during the pipeline execution could result in the IOP4 script terminating prematurely and only some results showing in the summary script, without clear hints indicating that this happened.
> Improve night summary script

- iop4lib/db/aperphotresult.py
- iop4lib/instruments/instrument.py
- iop4lib/utils/__init__.py
This corrects against small astrometric inaccuracies.
> Use centroid for aperture photometry

- iop4lib/db/astrosource.py
Specifies the convention used in the help text for the field, and in the doc string for the model. The convention used follows [SkyCoord defaults](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord).
Closes issue #136.
> Specify ICRS reference system for AstroSource coordinates.

- iop4lib/telescopes/telescope.py
This PR adds a check of the FTP credentials before trying to login and raises an exception if they were not defined. Before the error message was not very helpful.
> Add check for FTP credentials

- iop4api/templates/iop4api/index.html
This PR adds the option of querying a plot from URL parameters alone. This way we can link to the interactive plot in the gui easily (before, the plot query form had to be filled manually). The fields are now filled and the plot loaded automatically if the parameters are present.
> Allow querying plot from URL

- iop4admin/modeladmins/aperphotresult.py
- iop4admin/modeladmins/photopolresult.py
- iop4lib/db/aperphotresult.py
- iop4lib/db/masterbias.py
- iop4lib/instruments/cafos.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
Improves the admin for aperture photometry results, allows visually inspecting the apertures taken for each result.
> improve admin for aperture photometry results

- iop4lib/instruments/dipol.py
- iop4lib/utils/quadmatching.py
The quad hash is purposely invariant to flips and permutations. This results sometimes in a bad mapping from the sources in the photometry field and the ones in the polarimetry field. This can be observed in these two images of the same source, where one is correctly mapped, and the other one is not.
ReducedFit 242884
OSN-T090/2024-10-23/J0211_R_IAR-0371_DIPOL.fts
ReducedFit 242883
OSN-T090/2024-10-23/J0211_R_IAR-0370_DIPOL.fts
To resolve this ambiguity, this PR introduces a check of the flip status (sometimes introduced by MaximDL during data taking) and finds the linear transform that correctly takes into account this possible flip.
The new procedure correctly identifies the target source in both images above, both of which have a flip present. It also correctly identifies the source in …
> Fix quad matching

- iop4lib/instruments/instrument.py
- iop4lib/utils/__init__.py
Make sure that the source position does not fall too close to the borders of the image.
> Add checks of source position during aperture photometry

- iop4lib/instruments/cafos.py
Skip missing sources in CAFOS polarimetry groups and continue with reduction of other sources.
A source might be present in a polarimetry group but missing in one (or more) files. An example of this is a calibrator that it is too close to the border of the image and is missing in one of them, or its aperture photometry could not be computed.
This PR makes it so any source like that is skipped and the reduction is continued for the other sources.
> Skip missing sources in CAFOS polarimetry groups

- iop4lib/iop4.py
- Enables selecting files by source (in between given dates) and recomputing the results.
> iop4.py: enable recomputing results by astrosource

- iop4lib/instruments/dipol.py
Any error during the simbad query (e.g. because of internet connection) makes the calibration fail otherwise.
> Wrap Simbad query in try except during calibration

- iop4lib/iop4_night_summary.html
- iop4lib/iop4_night_summary.py
This PR improves the night summary by:
- Making the plots in the night summary clickable, linking to the interactive plot in the web gui.
- Fixing the plotting of previous night results. Results from the previous night, if available, are now plotted when the new night has only one point, to allow a comparison.
- Improves the style.
> Link to plot web gui in summary, fix plot

- iop4lib/db/photopolresult.py
- iop4lib/instruments/cafos.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
- iop4lib/instruments/osn_cameras.py
- Adds a fwhm field to PhotoPolResult.
- Ensure that aperpix, aperas and fwhm are always saved when creating a PhotoPolResult.
> Add fwhm, fix aperpix and aperas in PhotoPolResult
