juanep97/iop4

- README.md
> add zenodo badge with DOI, put badges at the top

- .github/workflows/release-drafter.yml
See e.g. https://github.com/release-drafter/release-drafter/issues/1350
> Add write permissions to create draft release

- iop4admin/modeladmins/fitfile.py
- iop4admin/modeladmins/masterbias.py
- iop4admin/modeladmins/masterdark.py
- iop4admin/modeladmins/masterflat.py
- iop4lib/db/masterbias.py
- iop4lib/db/masterdark.py
- iop4lib/db/masterflat.py
- iop4lib/db/rawfit.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
This PR:
- adds a `flags` field to MasterBias, MasterDark and MasterFlat models.
- adds 'IGNORE' as a possible flag to these flags fields.
- adds the possibility of setting and unsetting this flag in bulk in the admin change list:
> Adds option to ignore master calibration files

- iop4api/templates/iop4api/index.html
- iop4api/templates/iop4api/plot.html
- iop4api/views/plot.py
This PR:
- solves #60
- removes unused fmt parameter in the plot view
> iop4api: allow selecting band in plot form

- iop4lib/db/photopolresult.py
This PR improves host correction:
- ignoring flagged values during magnitude interpolation
- removing unnecessary db access
> Fix host correction

- iop4api/templates/iop4api/index.html
Some bug in last versions are making web gui break, this freezes the version to 3.4.9
https://github.com/vuejs/core/blob/main/CHANGELOG.md
> Freeze vuejs version

- iop4lib/instruments/instrument.py
> use only source calibrators

- .github/workflows/deploy_pypi.yml
The test worked (with test pypi repository): [https://github.com/juanep97/iop4/actions/runs/8361550838](https://github.com/juanep97/iop4/actions/runs/8361550838).
> Publish tagged releases to PyPI

- README.md
After hosting iop4 in PyPI, iop4 installation instructions can be eased.
Also updated citation of Zenodo reference.
> Update installation instructions and update citation

- README.md
Remove version from BibTeX entry example.
> Remove version from BibTeX entry example

- iop4lib/iop4_night_summary.html
- iop4lib/iop4_night_summary.py
When there are any files in error, add a link to these files.
> Add links to summary

- iop4admin/modeladmins/astrosource.py
Improve the AstroSource admin: 
- Adding a link to the last reduced fit in which the source was identified.
- Adding a column showing the average R magnitude for the last night with results from the source.
> Improve AstroSource admin

- iop4lib/instruments/instrument.py
Until now, for all instruments except DIPOL, `get_header_hintobject` would only try to match the OBJECT keyword or equivalent with the source names in the catalog, only in IAU format. This will attempt to match also the alternative name, with a more relaxed format, improving the changes of returning a match even when the observers take some freedom in setting the source name in the header, as it usually happens (and was already implemented in DIPOL).
We might think of making this relaxation optional, not to incur in false matches routinely.
> More relaxed and resilant get_header_hintobject

- iop4admin/modeladmins/astrosource.py
It was not displaying the last reduced file.
> Fix AstroSource admin

- iop4lib/instruments/instrument.py
It was stopping if there were several targets, one without calibrators.
> Fix compute_relative_photometry

- README.md
- docs/data_reduction_details.rst
- docs/iop4_concepts.rst
- docs/serving_iop4_in_production.rst
This PR improves the documentation. Changes:
- Add data directory description.
- Add instructions on how to set up a cron job.
- Add instructions on how to share the data directory.
> Improve docs

- iop4lib/telescopes/cahat220.py
- iop4lib/telescopes/osnt090.py
- iop4lib/telescopes/osnt150.py
- iop4lib/telescopes/telescope.py
> Fix override of FTP credentials

- iop4admin/modeladmins/astrosource.py
- iop4admin/modeladmins/reducedfit.py
- iop4admin/templates/iop4admin/view_fitdetails.html
- iop4lib/db/astrosource.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
- iop4lib/iop4_night_summary.py
- iop4lib/utils/__init__.py
- iop4lib/utils/plotting.py
- tests/conftest.py
> Allow multiple other names in AstroSource

- docs/iop4_concepts.rst
- iop4api/views/catalog.py
- iop4api/views/index.py
- iop4lib/db/astrosource.py
- iop4lib/db/fitfilemodel.py
- iop4lib/enums.py
- iop4lib/instruments/cafos.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
- iop4lib/instruments/osn_cameras.py
- iop4lib/iop4_night_summary.py
- iop4lib/utils/__init__.py
- tests/conftest.py
- tests/test_caha_cafos.py
- tests/test_osnt090_andor.py
> Remove SRCTYPES.CALIBRATOR

- .github/workflows/ci.yml
- docs/recipes/02_database_queries.py
- pyproject.toml
Related to:
https://github.com/juanep97/iop4/pull/127#issuecomment-2286868583
https://github.com/juanep97/iop4/pull/127#issuecomment-2315626056
> Test python 3.11 in CI

- iop4lib/utils/__init__.py
> Fix check of FLIP in DIPOL images in get_angle_from_history

- iop4admin/modeladmins/astrosource.py
Increase the maximum allowed std for the magnitude when adding calibrators from PanSTARRS, and sort so the ones with less std are prioritized.
> add_field_stars_from_panstarrs: increase MAX_MAG_STD, sort

- iop4lib/instruments/dipol.py
- iop4lib/iop4.py
- Use the appropriate transformations to get the translation between quads. 
- Remove unused imports.
> Improve quad matching

- iop4admin/templates/iop4admin/view_fitdetails.html
- iop4admin/views/fitfile.py
Adds a link to go easily from the reduced fit page to the results.
> Show results from each image in admin

- iop4admin/modeladmins/astrosource.py
- iop4admin/modeladmins/reducedfit.py
- iop4lib/instruments/cafos.py
- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
- iop4lib/instruments/osn_cameras.py
- iop4lib/iop4.py
- iop4lib/iop4_night_summary.html
- iop4lib/iop4_night_summary.py
- iop4lib/utils/__init__.py
- iop4lib/utils/astrometry.py
Code refactoring to remove duplicated and unused code, fix some bugs related to new keywords, and other small improvements.
> Code refactor, add new FILTER kw, fix small bugs

- iop4admin/modeladmins/astrosource.py
- iop4api/static/iop4api/gui.js
- iop4api/templates/iop4api/explore.html
- iop4api/templates/iop4api/index.html
- iop4api/views/data.py
- iop4api/views/index.py
- iop4api/views/log.py
- iop4lib/db/astrosource.py
- iop4lib/db/fitfilemodel.py
- iop4lib/iop4_night_summary.py
- Fixes bug in the web log viewer (permission name was wrong making the superuser the only one able to view them).
- Adds other source names to the source list displayed in the web gui.
- Adds the last night date next to the last night mag in the astrosource admin page.
- Fixes the time range of the link to the interactive plot in the night summary, so it shows results from previous night only when there is a single point in the summary's night. This is the same behavior as the static plot in the summary.
- Fixes some bugs related to the web gui (filtering, table creation).
- Style.
> Improve web gui and night summary

- tests/test_generic.py
Fixes tests after merging PR #170.
> Fix test_host_correction_data_load

- iop4lib/instruments/instrument.py
This PR fixes a bug occurring during aperture estimation and source position correction that caused these to fail often. It also completes PR #172, that removed some now unused functions but did not include the changes that replaced those functions.
> fix bug: aperture estimation, position correction

- iop4lib/instruments/dipol.py
- iop4lib/instruments/instrument.py
General improvements for DIPOL instument.
> Fix DIPOL header hint coords, instrumental polarization, quads
